title: 你的名字 | Academic Homepage
name: 你的名字
email: your@email.com
description: Short bio here. Replace with your research interests and current position.

remote_theme: alshedivat/al-folio@v0.4.3

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-sitemap


navbar:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Projects
    url: /projects/
  - title: CV
    url: /assets/cv.pdf
