title: Ruiyao Liu | Academic Homepage
name: Ruiyao Liu
email: ruiyaoliu@my.unt.edu
description: >-
  Short bio here. Replace with your research interests and current position.
url: ""     # GitHub Pages 会自动设置
baseurl: ""

lang: en
timezone: America/Chicago

remote_theme: alshedivat/al-folio@v0.4.3

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-scholar
  - kramdown-parser-gfm

collections:
  news:
    output: true
    permalink: /news/:path/

navbar:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Projects
    url: /projects/
  - title: CV
    url: /assets/cv.pdf

scholar:
  style: ieee
  bibliography: _bibliography/papers.bib
  bibliography_template: bibliography
  sort_by: year, month
  order: descending

paginate: 5
markdown: kramdown
kramdown:
  input: GFM
