title: 你的名字 | Academic Homepage
remote_theme: alshedivat/al-folio@v0.4.3
plugins:
  - jekyll-remote-theme
  - jekyll-scholar
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - kramdown-parser-gfm
navbar:
  - title: Home
    url: /
  - title: Publications
    url: /publications/
  - title: Projects
    url: /projects/
  - title: CV
    url: /assets/cv.pdf
scholar:
  bibliography: _bibliography/papers.bib
  style: ieee
